[package]
name = "rusty-scratch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json="0.12.4"
zip="0.6.2"
reqwest={version="0.11.11",features=["blocking"]}
rand="0.8.5"